### ISSUE TITLE
Unstable landing page search functionality. 

### ISSUE THREAD

**Issue by TundeMichael** [numahealth/Asknuma#4]
Apart from issue #2 resolved, the search functionality breaks occasionally depending of search text especially if the text has not been captured in the search history table. I will need to investigate to really get the root cause. Before proposing a solution. 

**Tasks**
- [ ] Create background process to scan articles + blogs  
- [ ] Test the new search functionality 
- [ ] Create contingency pages for when a users search does not match anything found in articles or blogs found on in the DB.

**Comment by TundeMichael** [comment]
To simulate the error, type a custom text into the search box (don't select from the dropdown option and make sure your search term is unique) and hit the enter key on your keyboard, the app will break

**Comment by TundeMichael** [comment]
Also note that the search box wouldn't allow you to search for a custom text with the search button. It clears every custom text. You can only use the search button if you select from the dropdown

**Comment by tobiobisanya** [comment]
Agreed Plan for Search functionality: 

1. Leave current search flow created by Unyscape as it is - with the cascade from Search Key Words & Phrases --> Symptoms --> Symptom Groups related to particular diseases.
2. Create secondary background process for natural language searches users will undertake by **not** selecting one of our Search Keywords or Phrases. This background process will search Articles + Blog posts within the CMS to look for the most relevant page to display to a user based on the text the user has inputed. **If** this process cannot find any information relevant to the users search - it should present the user with a page that suggests the user speak to a doctor (include the "Ask A Doctor" button) or email info@numa.io for more assistance on their query.

**Comment by TundeMichael** [comment]
Please @tobiobisanya review this issue at /v2/ (version 2 URL) and if satisfied, you can just close the issue.

**Comment by tobiobisanya** [comment]
I'm still getting an error message on this free text search. see picture sent via skype
